/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Base64File } from './base64File';

export class EditDocumentJsonFile {
    'editAction': EditDocumentJsonFile.EditActionEnum;
    'file'?: Base64File;
    'fileUrl'?: string | null;
    'id'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "editAction",
            "baseName": "editAction",
            "type": "EditDocumentJsonFile.EditActionEnum"
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "Base64File"
        },
        {
            "name": "fileUrl",
            "baseName": "fileUrl",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EditDocumentJsonFile.attributeTypeMap;
    }
}

export namespace EditDocumentJsonFile {
    export enum EditActionEnum {
        Add = <any> 'Add',
        Update = <any> 'Update',
        Remove = <any> 'Remove'
    }
}
